# Informations du site
title: "Victor Cardoso"
description: "Développeur Web Full-Stack passionné par les technologies modernes"
author: Victor Cardoso
email: vicardoso@sfr.fr
baseurl: ""
url: "https://vicardoso.github.io"
github_username: vicardoso

# Configuration du thème
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Paramètres personnalisés
lang: fr
timezone: Europe/Paris

# Navigation principale
header_pages:
  - about.md
  - skills.md
  - projects.md
  - contact.md

# Réseaux sociaux
social_links:
  github: vicardoso
  linkedin: victor-cardoso
  email: vicardoso@sfr.fr

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experiences:
    output: true
    permalink: /experiences/:path/

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git