title: "Cardoso Victor"
description: "Développeur Web Full-Stack passionné par les technologies modernes"
email: vicardoso@sfr.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vicardoso.github.io" # the base hostname & protocol for your site
github_username: vicardoso

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Personnalisation du thème
color-scheme: auto
show_downloads: false

# Configuration SASS
sass:
  style: compressed
  sass_dir: _sass

# Navigation
navigation:
  - name: À propos
    link: "#about"
  - name: Compétences
    link: "#skills"
  - name: Expériences
    link: "#projects"
  - name: Parcours
    link: "#professional-background"
  - name: Contact
    link: "#contact"