title: "Cardoso Victor"
email: vicardoso@sfr.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vicardoso.github.io" # the base hostname & protocol for your site
github_username:  vicardoso

# theme: minima