title: "Cardoso Victor"
email: vicardoso@sfr.fr
description: >- 
  Ce site présente mon parcours professionnel, mes projets et mes compétences en tant que développeur web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vicardoso.github.io" # the base hostname & protocol for your site
github_username:  vicardoso

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed